### ISSUE TITLE
Einige Fehler nach der Installation

### ISSUE THREAD

**Issue by nephx** [polarwinkel/GradeMan2#3]
Hallo,
ich bin per Zufall auf das Programm gestoßen, klingt genau nach dem, was ich brauche, aber etliche Dinge funktionieren hier nicht richtig.

Wenn ich Schüler per csv-Liste einfügen will erhalte ich
> Internal Server Error
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Denselben Fehler bekomme ich, wenn ich auf eine angelegte Klasse klicke oder auf Einträge im Stundenplan.
Datenbank neu laden gibt mir
> 404: Not found

Ich hatte allerdings das Gefühl, dass es bei der Erstinstallation gestern mehr lief. Gibt es mehr für ein Reset zu tun als die Datenbank und config-file zu löschen?
Gibt es irgendeine Art von Anleitung, wie das Video zur letzten Version?

Installation auf KDE Neon über das deb-Paket 2.0.0

Auf jeden Fall Danke für das Projekt, wenn ich's ans Laufen kriege (und es tut was es verspricht :)) wäre das genau das, was ich suche...

**Comment by nephx** [comment]
Sorry, hab selber was rausgefunden. 
Wenn ich in den Einstellungen _debug_ deaktiviere läufts...

**Comment by polarwinkel** [comment]
Moin,
danke für die Hinweise!
Der debug-mode soll natürlich nicht an sein nach der Installation, werde ich fixen für das nächste release.
Nach den von dir beschriebenen Fehlern mit dem debug-mode an schaue ich dann auch. Da ich im Moment an anderen Projekten bin dauert es noch einige Tage, aber es scheint ja nun erstmal bei dir zu laufen.

**Comment by polarwinkel** [comment]
Der Debug-Modus ist nun nicht mehr der Default (ab der nächsten Version, voraussichtlich im Sommer).
Ich lasse das Ticket noch offen um den zugrundeliegenden Fehler bis dahin noch mal zu checken.

**Comment by polarwinkel** [comment]
Ok, Fehler ist upstream behoben und kommt mit der nächsten Version.
Ursache war ein nicht initialisierter Wert für den Halbjahresübergang.
