### ISSUE TITLE
Letzte Stunde sehen beim erstellen einer neuen Stunde

### ISSUE THREAD

**Issue by c3schulto** [polarwinkel/GradeMan2#5]
Hallo Dirk,

ich benutze GradMan schon fast seit der Anfangszeit. Damals hast du auf meine Nachfrage die "Platzhalter-Bildchen" für Schüler ohne Foto in GradeMan aufgenommen.

Ich habe Grademan2 ganz neugierig installiert und ausprobiert. Mein gewohnter Workflow ist aber irgendwie unterbrochen. Ich fand es immer sehr hilfreich wenn ich im Stundenplan einen Kurs aufgerufen hatte, dass ich "neue Stunde" klicken konnte und dann die vorherige Stunde oben und die zu planende Stunde darunter sehen konnte. Dann konnte ich auch super per strg+a, strg+c, strg+v etwaige Einträge in die neue Stunde übernehmen und musste nur abwandeln oder ergänzen. Könntest du das ggf. in GM2 übernehmen? Das wäre klasse!

MfG, Christian

**Comment by polarwinkel** [comment]
Danke für den Hinweis, ich hatte es früher auch immer so gemacht, mittlerweile aber tatsächlich schon aus den Augen verloren.
Ich werde es bald einbauen wenn ich wieder dran gehe (bin gerade an einem anderen Projekt, das sollte aber bald fertig sein)

**Comment by c3schulto** [comment]
Moin. Vielen Dank. Kann ich denn theoretisch mit der derzeitigen Version starten und die Datenbank anschließend problemlos übernehmen? Liebe Grüße

**Comment by polarwinkel** [comment]
Die Datenbank hat definitiv einen stabilen update-Pfad, updates sind also immer möglich.
Nur zwischen dem alten GradeMan und GradeMan2 gibt es keine Möglichkeit des Datenbankupdates, der Umstieg macht also nur zum Schuljahreswechsel Sinn, sprich jetzt ;-)

Der wesentliche Unterschied der beiden ist, dass GradeMan2 klar als eigene Cloud-Anwendung konzipiert ist (läuft bei mir auf dem Heimserver), während der alte GradeMan als Ein-Geräte-Anwendung konzipiert war. Für beide ist aber der jeweilig andere Einsatz problemlos auch möglich.

**Comment by polarwinkel** [comment]
ich habe hierfür gerade einen neuen draft gepushed, muss aber noch schöner werden (Plan: bei Kursänderung wird die Anzeige aktualisiert)

**Comment by polarwinkel** [comment]
pushed to master, kommt mit der nächsten Version
